# Generated by Django 3.1.7 on 2021-03-28 06:14

from django.db import migrations

from media_system.models import Genre, Instrument


def create_data(apps, schema_editor):
    genres = ['Latino', 'Classic', 'Pop', 'Rock', 'Alternative']
    for genre in genres:
        Genre(name=genre).save()
    instruments = ['Guitar', 'Piano', 'Violin', 'Bass', 'Drums', 'Voice']
    for instrument in instruments:
        Instrument(name=instrument).save()


class Migration(migrations.Migration):
    dependencies = [
        ('media_system', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
