# Generated by Django 3.1.7 on 2021-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_media_system', '0001_initial'),
        ('users_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.musician'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.profile'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='musicians',
            field=models.ManyToManyField(related_name='instruments', to='users_system.Musician'),
        ),
        migrations.AddField(
            model_name='genre',
            name='musicians',
            field=models.ManyToManyField(related_name='genres', to='users_system.Musician'),
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users_system.musician'),
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.musician'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_system.publication'),
        ),
    ]
