# Generated by Django 3.1.7 on 2021-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_system', '0003_auto_20210326_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
