# Generated by Django 3.1.7 on 2021-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_system', '0004_auto_20210326_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aux_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
