# Generated by Django 3.1.7 on 2021-03-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_system', '0005_user_aux_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aux_token',
        ),
    ]
