# Generated by Django 3.1.7 on 2021-03-28 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('media_system', '0001_initial'),
        ('users_system', '0006_remove_user_aux_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('birth_date', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=60, null=True)),
                ('register_date', models.CharField(max_length=60, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizers', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_system.profile')),
            ],
            options={
                'db_table': 'organizers',
            },
            bases=('users_system.profile',),
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('musicians', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_system.profile')),
                ('artistic_name', models.CharField(max_length=100, null=True)),
                ('rating', models.FloatField(default=0)),
                ('genres', models.ManyToManyField(related_name='musicians', to='media_system.Genre')),
                ('instruments', models.ManyToManyField(related_name='musicians', to='media_system.Instrument')),
            ],
            options={
                'db_table': 'musicians',
            },
            bases=('users_system.profile',),
        ),
    ]
