# Generated by Django 3.1.7 on 2021-03-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_system', '0007_musician_organizer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.CharField(max_length=60)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users_system.musician')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.musician')),
            ],
            options={
                'db_table': 'following',
            },
        ),
    ]
