# Generated by Django 3.1.7 on 2021-04-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_system', '0009_auto_20210406_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
