# Generated by Django 3.1.7 on 2021-03-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_system', '0007_musician_organizer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=200)),
                ('update_time', models.CharField(max_length=60)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.musician')),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.profile')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_system.publication')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
