# Generated by Django 3.1.7 on 2021-03-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_system', '0003_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
