# Generated by Django 3.1.7 on 2021-04-21 16:29

from django.db import migrations

from social_media.seed import create_data


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
