# Generated by Django 3.1.7 on 2021-05-23 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_auto_20210421_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 20, 30, 7, 611668)),
        ),
    ]
