# Generated by Django 3.1.7 on 2021-05-23 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 20, 41, 54, 734690, tzinfo=utc)),
        ),
    ]
