# Generated by Django 3.1.7 on 2021-06-22 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_auto_20210523_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 5, 27, 16, 39022, tzinfo=utc)),
        ),
    ]
