# Generated by Django 3.1.7 on 2021-07-03 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_auto_20210622_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 4, 3, 8, 723304, tzinfo=utc)),
        ),
    ]
