# Generated by Django 3.1.7 on 2021-06-07 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0019_auto_20210607_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 16, 4, 8, 361636, tzinfo=utc)),
        ),
    ]
