# Generated by Django 3.1.7 on 2021-06-08 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0022_auto_20210608_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 16, 10, 532443, tzinfo=utc)),
        ),
    ]
