# Generated by Django 3.1.7 on 2021-06-08 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0025_auto_20210608_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 29, 12, 296808, tzinfo=utc)),
        ),
    ]
