# Generated by Django 3.1.7 on 2021-06-09 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0028_auto_20210608_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 3, 54, 0, 645528, tzinfo=utc)),
        ),
    ]
