# Generated by Django 3.1.7 on 2021-06-09 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0029_auto_20210608_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 4, 11, 25, 416139, tzinfo=utc)),
        ),
    ]
