# Generated by Django 3.1.7 on 2021-06-09 04:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0030_auto_20210608_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 4, 13, 22, 609111, tzinfo=utc)),
        ),
    ]
