# Generated by Django 3.1.7 on 2021-06-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_auto_20210421_1129'),
        ('accounts', '0002_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'contract_states',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('reference', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('amount', models.FloatField(null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='ReservationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'reservation_states',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('date', models.CharField(max_length=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.event')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.musician')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.reservationstate')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('score', models.FloatField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='agreements.contract')),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.contractstate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.event'),
        ),
        migrations.AddField(
            model_name='contract',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.musician'),
        ),
    ]
