# Generated by Django 3.1.7 on 2021-04-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0002_auto_20210417_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('reference', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120, null=True)),
                ('amount', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'contract_states',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('score', models.FloatField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='agreements.contract')),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.contractstate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
        migrations.AddField(
            model_name='contract',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.musician'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer'),
        ),
    ]
