# Generated by Django 3.1.7 on 2021-04-17 20:49

from django.db import migrations

from agreements.seed import create_data


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
