# Generated by Django 3.1.7 on 2021-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20210421_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'reservation_states',
            },
        ),
    ]
