# Generated by Django 3.1.7 on 2021-06-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210421_1129'),
        ('accounts', '0002_profile_image_url'),
        ('agreements', '0003_reservationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('reference', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('amount', models.FloatField(null=True)),
                ('state', models.CharField(max_length=40)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='accounts.musician')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
