# Generated by Django 3.1.7 on 2021-06-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image_url'),
        ('agreements', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('date', models.CharField(max_length=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.event')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.musician')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
