# Generated by Django 3.1.7 on 2021-06-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image_url'),
        ('agreements', '0005_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='musician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.musician'),
        ),
    ]
