# Generated by Django 3.1.7 on 2021-04-21 16:28

from django.db import migrations

from agreements.seed import create_data_reservations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_contract_event'),
    ]

    operations = [
        migrations.RunPython(create_data_reservations),
    ]
