# Generated by Django 3.1.7 on 2021-03-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_system', '0001_initial'),
        ('users_system', '0007_musician_organizer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.musician'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_system.organizer'),
        ),
    ]
