# Generated by Django 3.1.7 on 2021-03-28 07:17

from django.db import migrations

from contract_system.models import ContractState


def create_data(app, schema_editor):
    states = ['unanswered', 'progress', 'cancelled', 'finalized']
    for state in states:
        ContractState(state=state).save()


class Migration(migrations.Migration):
    dependencies = [
        ('contract_system', '0002_auto_20210328_0216'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
