# Generated by Django 3.1.7 on 2021-03-28 07:17

from django.db import migrations

def create_data(app, )


class Migration(migrations.Migration):

    dependencies = [
        ('contract_system', '0002_auto_20210328_0216'),
    ]

    operations = [
    ]
