# Generated by Django 3.1.7 on 2021-04-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_system', '0003_auto_20210417_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
