# Generated by Django 3.1.7 on 2021-03-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_system', '0003_auto_20210328_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('score', models.FloatField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='contract_system.contract')),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
    ]
